# Generated by Django 5.0.3 on 2024-03-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('announce', models.CharField(max_length=250, verbose_name='Анонс')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('date_time', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
